import { BUILTIN_QUESTION_TYPES } from '../registry'
import { MISTAKES_UNSCORABLE, type RuntimeQuestionTypeConfig, type ScoreQuestionResult } from '../scoring'

export type ScoringCase = {
	name: string
	typeKey: string
	key: unknown
	answer: unknown
	expected: ScoreQuestionResult
}

const UNSCORABLE = MISTAKES_UNSCORABLE

export const SCORING_TYPES_MAP: Record<string, RuntimeQuestionTypeConfig> = {
	...Object.fromEntries(
		BUILTIN_QUESTION_TYPES.map((item) => [
			item.key,
			{ key: item.key, uiTemplate: item.uiTemplate, scoringRule: item.scoringRule },
		])
	),
	custom_sequence: {
		key: 'custom_sequence',
		uiTemplate: 'sequence_digits',
		scoringRule: {
			formula: 'tiers',
			mistakeMetric: 'hamming_digits',
			correctPoints: 3,
			tiers: [
				{ maxMistakes: 1, points: 2 },
				{ maxMistakes: 2, points: 1 },
			],
		},
	},
	tiers_unsorted_fractional: {
		key: 'tiers_unsorted_fractional',
		uiTemplate: 'sequence_digits',
		scoringRule: {
			formula: 'tiers',
			mistakeMetric: 'hamming_digits',
			correctPoints: 2,
			tiers: [
				{ maxMistakes: 3, points: 0.5 },
				{ maxMistakes: 1, points: 1.5 },
			],
		},
	},
	one_mistake_clamped: {
		key: 'one_mistake_clamped',
		uiTemplate: 'sequence_digits',
		scoringRule: {
			formula: 'one_mistake_partial',
			mistakeMetric: 'hamming_digits',
			correctPoints: 2,
			oneMistakePoints: 3,
		},
	},
	one_mistake_fractional: {
		key: 'one_mistake_fractional',
		uiTemplate: 'sequence_digits',
		scoringRule: {
			formula: 'one_mistake_partial',
			mistakeMetric: 'hamming_digits',
			correctPoints: 2,
			oneMistakePoints: 0.5,
		},
	},
	broken_rule: {
		key: 'broken_rule',
		uiTemplate: 'sequence_digits',
		scoringRule: {},
	},
}

export const SINGLE_CHOICE_SCORING_CASES: ScoringCase[] = [
	{
		name: 'radio: верный вариант',
		typeKey: 'radio',
		key: 'option_a',
		answer: 'option_a',
		expected: { maxPoints: 1, earnedPoints: 1, isCorrect: true, mistakesCount: 0 },
	},
	{
		name: 'radio: неверный вариант',
		typeKey: 'radio',
		key: 'option_a',
		answer: 'option_b',
		expected: { maxPoints: 1, earnedPoints: 0, isCorrect: false, mistakesCount: 1 },
	},
	{
		name: 'radio: числовой ключ 1 против ответа "1"',
		typeKey: 'radio',
		key: 1,
		answer: '1',
		expected: { maxPoints: 1, earnedPoints: 1, isCorrect: true, mistakesCount: 0 },
	},
	{
		name: 'radio: числовой ответ 2 против ключа "2"',
		typeKey: 'radio',
		key: '2',
		answer: 2,
		expected: { maxPoints: 1, earnedPoints: 1, isCorrect: true, mistakesCount: 0 },
	},
	{
		name: 'radio: неотвеченный вопрос (null) — одна ошибка, 0 баллов',
		typeKey: 'radio',
		key: 'a',
		answer: null,
		expected: { maxPoints: 1, earnedPoints: 0, isCorrect: false, mistakesCount: 1 },
	},
	{
		name: 'radio: ответ формы multi_choice — одна ошибка',
		typeKey: 'radio',
		key: 'a',
		answer: ['a'],
		expected: { maxPoints: 1, earnedPoints: 0, isCorrect: false, mistakesCount: 1 },
	},
	{
		name: 'radio: неразбираемый ключ null — одна ошибка',
		typeKey: 'radio',
		key: null,
		answer: 'a',
		expected: { maxPoints: 1, earnedPoints: 0, isCorrect: false, mistakesCount: 1 },
	},
]

export const MULTI_CHOICE_SCORING_CASES: ScoringCase[] = [
	{
		name: 'checkbox: точный набор',
		typeKey: 'checkbox',
		key: ['1', '2', '3'],
		answer: ['1', '2', '3'],
		expected: { maxPoints: 2, earnedPoints: 2, isCorrect: true, mistakesCount: 0 },
	},
	{
		name: 'checkbox: одна ошибка',
		typeKey: 'checkbox',
		key: ['1', '2', '3'],
		answer: ['1', '2', '4'],
		expected: { maxPoints: 2, earnedPoints: 1, isCorrect: false, mistakesCount: 1 },
	},
	{
		name: 'checkbox: несколько ошибок',
		typeKey: 'checkbox',
		key: ['1', '2', '3'],
		answer: ['1', '4', '5'],
		expected: { maxPoints: 2, earnedPoints: 0, isCorrect: false, mistakesCount: 2 },
	},
	{
		name: 'checkbox с числовыми ID в correctAnswer',
		typeKey: 'checkbox',
		key: [1, 2, 3],
		answer: ['1', '2', '3'],
		expected: { maxPoints: 2, earnedPoints: 2, isCorrect: true, mistakesCount: 0 },
	},
	{
		name: 'checkbox: порядок выбора не важен',
		typeKey: 'checkbox',
		key: ['1', '2', '3'],
		answer: ['3', '1', '2'],
		expected: { maxPoints: 2, earnedPoints: 2, isCorrect: true, mistakesCount: 0 },
	},
	{
		name: 'checkbox: лишний вариант — одна ошибка',
		typeKey: 'checkbox',
		key: ['1', '2', '3'],
		answer: ['1', '2', '3', '4'],
		expected: { maxPoints: 2, earnedPoints: 1, isCorrect: false, mistakesCount: 1 },
	},
	{
		name: 'checkbox: пропущенный вариант — одна ошибка',
		typeKey: 'checkbox',
		key: ['1', '2', '3'],
		answer: ['1', '2'],
		expected: { maxPoints: 2, earnedPoints: 1, isCorrect: false, mistakesCount: 1 },
	},
	{
		name: 'checkbox: повтор в ответе считается одним выбором',
		typeKey: 'checkbox',
		key: ['1'],
		answer: ['1', '1'],
		expected: { maxPoints: 2, earnedPoints: 2, isCorrect: true, mistakesCount: 0 },
	},
	{
		name: 'checkbox: числовые ID в ответе',
		typeKey: 'checkbox',
		key: ['1', '2'],
		answer: [1, '2'],
		expected: { maxPoints: 2, earnedPoints: 2, isCorrect: true, mistakesCount: 0 },
	},
	{
		name: 'checkbox: пустой выбор при двух верных — две ошибки',
		typeKey: 'checkbox',
		key: ['1', '2'],
		answer: [],
		expected: { maxPoints: 2, earnedPoints: 0, isCorrect: false, mistakesCount: 2 },
	},
	{
		name: 'checkbox: неотвеченный вопрос (null)',
		typeKey: 'checkbox',
		key: ['1', '2'],
		answer: null,
		expected: { maxPoints: 2, earnedPoints: 0, isCorrect: false, mistakesCount: UNSCORABLE },
	},
	{
		name: 'checkbox: ответ формы single_choice неразбираем',
		typeKey: 'checkbox',
		key: ['a'],
		answer: 'a',
		expected: { maxPoints: 2, earnedPoints: 0, isCorrect: false, mistakesCount: UNSCORABLE },
	},
	{
		name: 'checkbox: ключ-строка неразбираем',
		typeKey: 'checkbox',
		key: '1',
		answer: ['1'],
		expected: { maxPoints: 2, earnedPoints: 0, isCorrect: false, mistakesCount: UNSCORABLE },
	},
]

export const MATCHING_SCORING_CASES: ScoringCase[] = [
	{
		name: 'matching: точное соответствие',
		typeKey: 'matching',
		key: { a: '1', b: '2', c: '3' },
		answer: { a: '1', b: '2', c: '3' },
		expected: { maxPoints: 2, earnedPoints: 2, isCorrect: true, mistakesCount: 0 },
	},
	{
		name: 'matching: одна ошибка',
		typeKey: 'matching',
		key: { a: '1', b: '2', c: '3' },
		answer: { a: '1', b: '3', c: '3' },
		expected: { maxPoints: 2, earnedPoints: 1, isCorrect: false, mistakesCount: 1 },
	},
	{
		name: 'matching: несколько ошибок',
		typeKey: 'matching',
		key: { a: '1', b: '2', c: '3' },
		answer: { a: '2', b: '3', c: '1' },
		expected: { maxPoints: 2, earnedPoints: 0, isCorrect: false, mistakesCount: 3 },
	},
	{
		name: 'matching: числовые значения в ответе',
		typeKey: 'matching',
		key: { a: '1', b: '2', c: '3' },
		answer: { a: 1, b: 2, c: 3 },
		expected: { maxPoints: 2, earnedPoints: 2, isCorrect: true, mistakesCount: 0 },
	},
	{
		name: 'matching: неполное отображение — пропущенная пара считается ошибкой',
		typeKey: 'matching',
		key: { a: '1', b: '2', c: '3' },
		answer: { a: '1', b: '2' },
		expected: { maxPoints: 2, earnedPoints: 1, isCorrect: false, mistakesCount: 1 },
	},
	{
		name: 'matching: лишняя пара в ответе не считается',
		typeKey: 'matching',
		key: { a: '1', b: '2', c: '3' },
		answer: { a: '1', b: '2', c: '3', d: '4' },
		expected: { maxPoints: 2, earnedPoints: 2, isCorrect: true, mistakesCount: 0 },
	},
	{
		name: 'matching: пустое отображение — ошибка на каждую пару ключа',
		typeKey: 'matching',
		key: { a: '1', b: '2', c: '3' },
		answer: {},
		expected: { maxPoints: 2, earnedPoints: 0, isCorrect: false, mistakesCount: 3 },
	},
	{
		name: 'matching: неотвеченный вопрос (null)',
		typeKey: 'matching',
		key: { a: '1' },
		answer: null,
		expected: { maxPoints: 2, earnedPoints: 0, isCorrect: false, mistakesCount: UNSCORABLE },
	},
	{
		name: 'matching: ответ-массив неразбираем',
		typeKey: 'matching',
		key: { a: '1' },
		answer: ['1'],
		expected: { maxPoints: 2, earnedPoints: 0, isCorrect: false, mistakesCount: UNSCORABLE },
	},
	{
		name: 'matching: значение null в паре делает ответ неразбираемым',
		typeKey: 'matching',
		key: { a: '1', b: '2' },
		answer: { a: '1', b: null },
		expected: { maxPoints: 2, earnedPoints: 0, isCorrect: false, mistakesCount: UNSCORABLE },
	},
	{
		name: 'matching: пустой ключ неразбираем',
		typeKey: 'matching',
		key: {},
		answer: { a: '1' },
		expected: { maxPoints: 2, earnedPoints: 0, isCorrect: false, mistakesCount: UNSCORABLE },
	},
]

export const SHORT_TEXT_SCORING_CASES: ScoringCase[] = [
	{
		name: 'short_answer: совпадение без учёта регистра и пробелов',
		typeKey: 'short_answer',
		key: 'митоз',
		answer: ' МИТОЗ ',
		expected: { maxPoints: 1, earnedPoints: 1, isCorrect: true, mistakesCount: 0 },
	},
	{
		name: 'short_answer: неверный ответ даёт 0 баллов',
		typeKey: 'short_answer',
		key: 'митоз',
		answer: 'мейоз',
		expected: { maxPoints: 1, earnedPoints: 0, isCorrect: false, mistakesCount: 1 },
	},
	{
		name: 'short_answer_variants: любой из допустимых вариантов засчитывается',
		typeKey: 'short_answer_variants',
		key: ['эксперимент', 'моделирование'],
		answer: 'МОДЕЛИРОВАНИЕ',
		expected: { maxPoints: 1, earnedPoints: 1, isCorrect: true, mistakesCount: 0 },
	},
	{
		name: 'short_answer_variants: ответ вне набора даёт 0 баллов',
		typeKey: 'short_answer_variants',
		key: ['эксперимент', 'моделирование'],
		answer: 'наблюдение',
		expected: { maxPoints: 1, earnedPoints: 0, isCorrect: false, mistakesCount: 1 },
	},
	{
		name: 'short_answer: пробелы внутри слова убираются',
		typeKey: 'short_answer',
		key: 'митоз',
		answer: ' Ми Тоз ',
		expected: { maxPoints: 1, earnedPoints: 1, isCorrect: true, mistakesCount: 0 },
	},
	{
		name: 'D-11: ответ "1.50" против ключа "1.5" — строки различаются, одна ошибка',
		typeKey: 'short_answer',
		key: '1.5',
		answer: '1.50',
		expected: { maxPoints: 1, earnedPoints: 0, isCorrect: false, mistakesCount: 1 },
	},
	{
		name: 'D-11: числовой ключ 3142 против ответа "3142" — ноль ошибок',
		typeKey: 'short_answer',
		key: 3142,
		answer: '3142',
		expected: { maxPoints: 1, earnedPoints: 1, isCorrect: true, mistakesCount: 0 },
	},
	{
		name: 'D-11: числовой ключ 1.5 против ответа "1.50" — одна ошибка',
		typeKey: 'short_answer',
		key: 1.5,
		answer: '1.50',
		expected: { maxPoints: 1, earnedPoints: 0, isCorrect: false, mistakesCount: 1 },
	},
	{
		name: 'D-11: числовой ответ 3142 против ключа "3142" — ноль ошибок',
		typeKey: 'short_answer',
		key: '3142',
		answer: 3142,
		expected: { maxPoints: 1, earnedPoints: 1, isCorrect: true, mistakesCount: 0 },
	},
	{
		name: 'D-12: compact_text_in_set со строковым ключом неразбираем',
		typeKey: 'short_answer_variants',
		key: 'митоз',
		answer: 'митоз',
		expected: { maxPoints: 1, earnedPoints: 0, isCorrect: false, mistakesCount: UNSCORABLE },
	},
	{
		name: 'D-12: compact_text_equal с ключом-массивом неразбираем',
		typeKey: 'short_answer',
		key: ['митоз'],
		answer: 'митоз',
		expected: { maxPoints: 1, earnedPoints: 0, isCorrect: false, mistakesCount: UNSCORABLE },
	},
	{
		name: 'short_answer_variants: нестроковые элементы ключа пропускаются',
		typeKey: 'short_answer_variants',
		key: [null, 'митоз'],
		answer: 'Митоз',
		expected: { maxPoints: 1, earnedPoints: 1, isCorrect: true, mistakesCount: 0 },
	},
	{
		name: 'short_answer_variants: пустой набор вариантов неразбираем',
		typeKey: 'short_answer_variants',
		key: [],
		answer: 'митоз',
		expected: { maxPoints: 1, earnedPoints: 0, isCorrect: false, mistakesCount: UNSCORABLE },
	},
	{
		name: 'short_answer: неотвеченный вопрос (null)',
		typeKey: 'short_answer',
		key: 'митоз',
		answer: null,
		expected: { maxPoints: 1, earnedPoints: 0, isCorrect: false, mistakesCount: UNSCORABLE },
	},
	{
		name: 'short_answer_variants: неотвеченный вопрос (null)',
		typeKey: 'short_answer_variants',
		key: ['митоз'],
		answer: null,
		expected: { maxPoints: 1, earnedPoints: 0, isCorrect: false, mistakesCount: UNSCORABLE },
	},
	{
		name: 'short_answer: пустая строка неразбираема',
		typeKey: 'short_answer',
		key: 'митоз',
		answer: '',
		expected: { maxPoints: 1, earnedPoints: 0, isCorrect: false, mistakesCount: UNSCORABLE },
	},
	{
		name: 'short_answer: строка из пробелов неразбираема',
		typeKey: 'short_answer',
		key: 'митоз',
		answer: '   ',
		expected: { maxPoints: 1, earnedPoints: 0, isCorrect: false, mistakesCount: UNSCORABLE },
	},
]

export const SEQUENCE_SCORING_CASES: ScoringCase[] = [
	{
		name: 'sequence: точный ответ',
		typeKey: 'sequence',
		key: '2314',
		answer: '2314',
		expected: { maxPoints: 2, earnedPoints: 2, isCorrect: true, mistakesCount: 0 },
	},
	{
		name: 'sequence: одна ошибка',
		typeKey: 'sequence',
		key: '2314',
		answer: '2315',
		expected: { maxPoints: 2, earnedPoints: 1, isCorrect: false, mistakesCount: 1 },
	},
	{
		name: 'sequence: несколько ошибок',
		typeKey: 'sequence',
		key: '2314',
		answer: '2415',
		expected: { maxPoints: 2, earnedPoints: 0, isCorrect: false, mistakesCount: 2 },
	},
	{
		name: 'sequence: перестановка соседних цифр',
		typeKey: 'sequence',
		key: '12345',
		answer: '12354',
		expected: { maxPoints: 2, earnedPoints: 1, isCorrect: false, mistakesCount: 1 },
	},
	{
		name: 'sequence: перестановка несоседних цифр',
		typeKey: 'sequence',
		key: '12345',
		answer: '14325',
		expected: { maxPoints: 2, earnedPoints: 0, isCorrect: false, mistakesCount: 2 },
	},
	{
		name: 'sequence из двух цифр: верна первая',
		typeKey: 'sequence',
		key: '12',
		answer: '11',
		expected: { maxPoints: 2, earnedPoints: 1, isCorrect: false, mistakesCount: 1 },
	},
	{
		name: 'sequence из двух цифр: верна вторая',
		typeKey: 'sequence',
		key: '12',
		answer: '22',
		expected: { maxPoints: 2, earnedPoints: 1, isCorrect: false, mistakesCount: 1 },
	},
	{
		name: 'sequence из двух цифр: цифры переставлены',
		typeKey: 'sequence',
		key: '12',
		answer: '21',
		expected: { maxPoints: 2, earnedPoints: 0, isCorrect: false, mistakesCount: 2 },
	},
	{
		name: 'sequence из трёх цифр: точный ответ',
		typeKey: 'sequence',
		key: '251',
		answer: '251',
		expected: { maxPoints: 2, earnedPoints: 2, isCorrect: true, mistakesCount: 0 },
	},
	{
		name: 'sequence из трёх цифр: неверна первая',
		typeKey: 'sequence',
		key: '251',
		answer: '351',
		expected: { maxPoints: 2, earnedPoints: 1, isCorrect: false, mistakesCount: 1 },
	},
	{
		name: 'sequence из трёх цифр: неверна последняя',
		typeKey: 'sequence',
		key: '251',
		answer: '259',
		expected: { maxPoints: 2, earnedPoints: 1, isCorrect: false, mistakesCount: 1 },
	},
	{
		name: 'sequence из трёх цифр: цифры переставлены',
		typeKey: 'sequence',
		key: '251',
		answer: '521',
		expected: { maxPoints: 2, earnedPoints: 0, isCorrect: false, mistakesCount: 2 },
	},
	{
		name: 'custom_sequence (tiers): точный ответ',
		typeKey: 'custom_sequence',
		key: '1234',
		answer: '1234',
		expected: { maxPoints: 3, earnedPoints: 3, isCorrect: true, mistakesCount: 0 },
	},
	{
		name: 'custom_sequence (tiers): одна ошибка',
		typeKey: 'custom_sequence',
		key: '1234',
		answer: '1235',
		expected: { maxPoints: 3, earnedPoints: 2, isCorrect: false, mistakesCount: 1 },
	},
	{
		name: 'VALID-01: sequence с числовым correctAnswer (JSONB) засчитывается',
		typeKey: 'sequence',
		key: 1234,
		answer: '1234',
		expected: { maxPoints: 2, earnedPoints: 2, isCorrect: true, mistakesCount: 0 },
	},
	{
		name: 'VALID-01: sequence с числовым correctAnswer, неверный ответ',
		typeKey: 'sequence',
		key: 1234,
		answer: '9999',
		expected: { maxPoints: 2, earnedPoints: 0, isCorrect: false, mistakesCount: 4 },
	},
	{
		name: 'D2: ключ 1243, ответ 1234 — соседняя перестановка, одна ошибка',
		typeKey: 'sequence',
		key: '1243',
		answer: '1234',
		expected: { maxPoints: 2, earnedPoints: 1, isCorrect: false, mistakesCount: 1 },
	},
	{
		name: 'D2: точный ответ 1243',
		typeKey: 'sequence',
		key: '1243',
		answer: '1243',
		expected: { maxPoints: 2, earnedPoints: 2, isCorrect: true, mistakesCount: 0 },
	},
	{
		name: 'перестановка в ключе из трёх цифр 123/132 — исключение не действует, две ошибки',
		typeKey: 'sequence',
		key: '123',
		answer: '132',
		expected: { maxPoints: 2, earnedPoints: 0, isCorrect: false, mistakesCount: 2 },
	},
	{
		name: 'перестановка несоседних цифр 1234/3214 — две ошибки',
		typeKey: 'sequence',
		key: '1234',
		answer: '3214',
		expected: { maxPoints: 2, earnedPoints: 0, isCorrect: false, mistakesCount: 2 },
	},
	{
		name: 'ответ длиннее ключа на одну цифру 1234/12345 — одна ошибка',
		typeKey: 'sequence',
		key: '1234',
		answer: '12345',
		expected: { maxPoints: 2, earnedPoints: 1, isCorrect: false, mistakesCount: 1 },
	},
	{
		name: 'ответ длиннее ключа с соседней перестановкой 1234/21345 — исключение не действует',
		typeKey: 'sequence',
		key: '1234',
		answer: '21345',
		expected: { maxPoints: 2, earnedPoints: 0, isCorrect: false, mistakesCount: 3 },
	},
	{
		name: 'две соседние перестановки 1234/2143 — четыре ошибки',
		typeKey: 'sequence',
		key: '1234',
		answer: '2143',
		expected: { maxPoints: 2, earnedPoints: 0, isCorrect: false, mistakesCount: 4 },
	},
	{
		name: 'обратный порядок 1234/4321 — четыре ошибки',
		typeKey: 'sequence',
		key: '1234',
		answer: '4321',
		expected: { maxPoints: 2, earnedPoints: 0, isCorrect: false, mistakesCount: 4 },
	},
	{
		name: 'три несовпадения 1234/2314 — три ошибки',
		typeKey: 'sequence',
		key: '1234',
		answer: '2314',
		expected: { maxPoints: 2, earnedPoints: 0, isCorrect: false, mistakesCount: 3 },
	},
	{
		name: 'ключ с повтором 1123, ответ 1213 — соседняя перестановка, одна ошибка',
		typeKey: 'sequence',
		key: '1123',
		answer: '1213',
		expected: { maxPoints: 2, earnedPoints: 1, isCorrect: false, mistakesCount: 1 },
	},
	{
		name: 'tiers не по возрастанию: 0 ошибок — correctPoints',
		typeKey: 'tiers_unsorted_fractional',
		key: '12345',
		answer: '12345',
		expected: { maxPoints: 2, earnedPoints: 2, isCorrect: true, mistakesCount: 0 },
	},
	{
		name: 'tiers не по возрастанию: 1 ошибка (равна maxMistakes 1) — 1.5',
		typeKey: 'tiers_unsorted_fractional',
		key: '12345',
		answer: '12395',
		expected: { maxPoints: 2, earnedPoints: 1.5, isCorrect: false, mistakesCount: 1 },
	},
	{
		name: 'tiers не по возрастанию: 2 ошибки (maxMistakes 1 плюс один) — 0.5',
		typeKey: 'tiers_unsorted_fractional',
		key: '12345',
		answer: '12995',
		expected: { maxPoints: 2, earnedPoints: 0.5, isCorrect: false, mistakesCount: 2 },
	},
	{
		name: 'tiers не по возрастанию: 3 ошибки (равна maxMistakes 3) — 0.5',
		typeKey: 'tiers_unsorted_fractional',
		key: '12345',
		answer: '19995',
		expected: { maxPoints: 2, earnedPoints: 0.5, isCorrect: false, mistakesCount: 3 },
	},
	{
		name: 'tiers не по возрастанию: 4 ошибки (maxMistakes 3 плюс один) — 0',
		typeKey: 'tiers_unsorted_fractional',
		key: '12345',
		answer: '99995',
		expected: { maxPoints: 2, earnedPoints: 0, isCorrect: false, mistakesCount: 4 },
	},
	{
		name: 'one_mistake_partial: oneMistakePoints больше correctPoints ограничен correctPoints',
		typeKey: 'one_mistake_clamped',
		key: '12345',
		answer: '12395',
		expected: { maxPoints: 2, earnedPoints: 2, isCorrect: false, mistakesCount: 1 },
	},
	{
		name: 'one_mistake_partial: дробные баллы за одну ошибку сохраняются',
		typeKey: 'one_mistake_fractional',
		key: '12345',
		answer: '12395',
		expected: { maxPoints: 2, earnedPoints: 0.5, isCorrect: false, mistakesCount: 1 },
	},
	{
		name: 'one_mistake_partial: две ошибки — 0 баллов',
		typeKey: 'one_mistake_fractional',
		key: '12345',
		answer: '12995',
		expected: { maxPoints: 2, earnedPoints: 0, isCorrect: false, mistakesCount: 2 },
	},
	{
		name: 'неразбираемое правило {}: точный ответ по правилу шаблона по умолчанию',
		typeKey: 'broken_rule',
		key: '1234',
		answer: '1234',
		expected: { maxPoints: 2, earnedPoints: 2, isCorrect: true, mistakesCount: 0 },
	},
	{
		name: 'неразбираемое правило {}: одна ошибка по правилу шаблона по умолчанию',
		typeKey: 'broken_rule',
		key: '1234',
		answer: '1235',
		expected: { maxPoints: 2, earnedPoints: 1, isCorrect: false, mistakesCount: 1 },
	},
	{
		name: 'sequence: пробелы в ответе убираются',
		typeKey: 'sequence',
		key: '2314',
		answer: ' 23 14 ',
		expected: { maxPoints: 2, earnedPoints: 2, isCorrect: true, mistakesCount: 0 },
	},
	{
		name: 'sequence: числовой ответ',
		typeKey: 'sequence',
		key: '2314',
		answer: 2314,
		expected: { maxPoints: 2, earnedPoints: 2, isCorrect: true, mistakesCount: 0 },
	},
	{
		name: 'sequence: неотвеченный вопрос (null)',
		typeKey: 'sequence',
		key: '2314',
		answer: null,
		expected: { maxPoints: 2, earnedPoints: 0, isCorrect: false, mistakesCount: UNSCORABLE },
	},
	{
		name: 'sequence: ответ с нецифровым символом неразбираем',
		typeKey: 'sequence',
		key: '123',
		answer: '12a',
		expected: { maxPoints: 2, earnedPoints: 0, isCorrect: false, mistakesCount: UNSCORABLE },
	},
	{
		name: 'sequence: дробный числовой ключ неразбираем',
		typeKey: 'sequence',
		key: 1.5,
		answer: '15',
		expected: { maxPoints: 2, earnedPoints: 0, isCorrect: false, mistakesCount: UNSCORABLE },
	},
]
