/**
 * Публичные API роуты для прохождения тестов (для студентов)
 */
import { and, asc, count, desc, eq, gte, inArray, isNull, lte, sql } from 'drizzle-orm'
import { Router } from 'express'
import { z } from 'zod'

import { db } from '../../db/index.js'
import {
	answerKeys,
	appSettings,
	questions,
	testAssignments,
	testAttempts,
	testSessions,
	tests,
	topics,
} from '../../db/schema.js'
import { ApiError } from '../../lib/errors.js'
import { getQuestionTypeMapForTest } from '../../lib/tests/question-type-resolver.js'
import { scoreQuestionByType } from '../../lib/tests/scoring.js'
import { SubmitResultSchema } from '../../lib/tests/submit-result.js'
import { mergeTelemetryMaps } from '../../lib/tests/telemetry.js'
import { sessionRequired } from '../../middleware/auth/session.js'
import { validateUUID } from '../../middleware/validateParams.js'
import { storageService } from '../../services/storage/storage.js'

const router = Router()

// =============================================================================
// Zod Schemas
// =============================================================================

const SubmitAnswerValueSchema = z.union([z.string(), z.array(z.string()), z.record(z.string(), z.string())])

const TelemetrySchema = z.record(
	z.string().uuid(),
	z.object({
		timeSpentMs: z.number().int().nonnegative(),
		focusLossCount: z.number().int().nonnegative(),
		visitCount: z.number().int().nonnegative(),
	})
)

const SubmitAnswersSchema = z.object({
	answers: z.record(z.string().uuid(), SubmitAnswerValueSchema), // questionId -> answer
	clientAttemptId: z.string().uuid().optional(), // idempotency key generated by client
	telemetry: TelemetrySchema.optional(),
})

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i

const GRACE_PERIOD_MINUTES = 2
const DB_RETRY_ENABLED = process.env.DB_QUERY_RETRY !== '0'

// =============================================================================
// Helpers
// =============================================================================

function buildQuestionMarkdownCandidates(params: {
	storedPath: string | null
	topicSlug: string
	testSlug: string
	testId: string
	questionId: string
	fileName: 'prompt.md' | 'explanation.md'
}): string[] {
	const { storedPath, topicSlug, testSlug, testId, questionId, fileName } = params

	// Current canonical path:
	// topics/{topicSlug}/{testSlug}/questions/{questionId}/{fileName}
	//
	// Backward-compatible fallbacks:
	// - questions/{testId}/{fileName}
	// - {testId} used as test folder
	const candidates = [
		storedPath,
		`topics/${topicSlug}/${testSlug}/questions/${questionId}/${fileName}`,
		`topics/${topicSlug}/${testSlug}/questions/${testId}/${fileName}`,
		`topics/${topicSlug}/${testId}/questions/${questionId}/${fileName}`,
		`topics/${topicSlug}/${testId}/questions/${testId}/${fileName}`,
	].filter((value): value is string => typeof value === 'string' && value.length > 0)

	return [...new Set(candidates)]
}

async function readFirstMarkdown(candidates: string[]): Promise<string> {
	for (const candidate of candidates) {
		const content = await storageService.readFile(candidate)
		if (content.trim().length > 0) {
			return content
		}
	}
	return ''
}

function errorText(err: unknown): string {
	if (err instanceof Error) {
		const parts = [err.message]
		const cause = (err as Error & { cause?: unknown }).cause
		if (cause instanceof Error) parts.push(cause.message)
		return parts.join(' | ')
	}
	return String(err)
}

function isTransientDbError(err: unknown): boolean {
	const message = errorText(err).toLowerCase()
	return (
		message.includes('connection terminated unexpectedly') ||
		message.includes('query read timeout') ||
		message.includes('econnreset') ||
		message.includes('etimedout') ||
		message.includes('eai_again')
	)
}

async function withTransientDbRetry<T>(label: string, task: () => Promise<T>): Promise<T> {
	try {
		return await task()
	} catch (err) {
		if (!DB_RETRY_ENABLED || !isTransientDbError(err)) throw err
		// eslint-disable-next-line no-console
		console.warn(`[db-retry] ${label}: retry once after transient DB error`)
		await new Promise((resolve) => setTimeout(resolve, 120))
		return task()
	}
}

// =============================================================================
// Endpoints
// =============================================================================

// GET /api/tests/public/topics - список активных тем
router.get('/topics', async (_req, res, next) => {
	try {
		const rows = await db
			.select({
				id: topics.id,
				slug: topics.slug,
				title: topics.title,
				description: topics.description,
			})
			.from(topics)
			.where(eq(topics.isActive, true))
			.orderBy(asc(topics.order), asc(topics.title))

		res.json({ topics: rows })
	} catch (e) {
		next(e)
	}
})

// GET /api/tests/public/tests - список всех опубликованных тестов в активных темах
router.get('/tests', sessionRequired(), async (req, res, next) => {
	try {
		const userId = req.authUser!.id
		const isAdmin = req.authUser!.roles?.includes('admin') ?? false

		const baseQuery = db
			.select({
				id: tests.id,
				slug: tests.slug,
				title: tests.title,
				description: tests.description,
				showCorrectAnswer: tests.showCorrectAnswer,
				timeLimitMinutes: tests.timeLimitMinutes,
				passingScore: tests.passingScore,
				topicId: topics.id,
				topicSlug: topics.slug,
				topicTitle: topics.title,
				questionsCount: sql<number>`count(${questions.id})::int`.as('questionsCount'),
			})
			.from(tests)
			.innerJoin(topics, and(eq(tests.topicId, topics.id), eq(topics.isActive, true)))
			.leftJoin(questions, eq(questions.testId, tests.id))
			.where(eq(tests.isPublished, true))
			.$dynamic()

		const query = isAdmin
			? baseQuery
			: baseQuery.innerJoin(
					testAssignments,
					and(eq(testAssignments.testId, tests.id), eq(testAssignments.userId, userId))
				)

		const rows = await query
			.groupBy(tests.id, topics.id, topics.slug, topics.title)
			.orderBy(asc(topics.order), asc(topics.title), asc(tests.order), asc(tests.title))

		res.json({ tests: rows })
	} catch (e) {
		next(e)
	}
})

// GET /api/tests/public/topics/:slug/tests - список опубликованных тестов в теме
router.get('/topics/:slug/tests', sessionRequired(), async (req, res, next) => {
	try {
		const { slug } = req.params as { slug: string }
		const userId = req.authUser!.id
		const isAdmin = req.authUser!.roles?.includes('admin') ?? false

		const topic = await db.query.topics.findFirst({
			where: and(eq(topics.slug, slug), eq(topics.isActive, true)),
		})

		if (!topic) {
			return res.status(404).json({ error: 'Topic not found' })
		}

		const baseQuery = db
			.select({
				id: tests.id,
				slug: tests.slug,
				title: tests.title,
				description: tests.description,
				timeLimitMinutes: tests.timeLimitMinutes,
				passingScore: tests.passingScore,
				questionsCount: sql<number>`count(${questions.id})::int`.as('questionsCount'),
			})
			.from(tests)
			.leftJoin(questions, eq(questions.testId, tests.id))
			.where(and(eq(tests.topicId, topic.id), eq(tests.isPublished, true)))
			.$dynamic()

		const query = isAdmin
			? baseQuery
			: baseQuery.innerJoin(
					testAssignments,
					and(eq(testAssignments.testId, tests.id), eq(testAssignments.userId, userId))
				)

		const rows = await query.groupBy(tests.id).orderBy(asc(tests.order), asc(tests.title))

		res.json({ tests: rows, topicTitle: topic.title })
	} catch (e) {
		next(e)
	}
})

// GET /api/tests/public/topics/:topicSlug/tests/:testSlug - получить тест по slug темы и slug теста
router.get('/topics/:topicSlug/tests/:testSlug', sessionRequired(), async (req, res, next) => {
	try {
		const { topicSlug, testSlug } = req.params as { topicSlug: string; testSlug: string }

			const testRows = await withTransientDbRetry('public test by slug', () =>
				db
					.select({
						id: tests.id,
						slug: tests.slug,
						title: tests.title,
						description: tests.description,
						showCorrectAnswer: tests.showCorrectAnswer,
						timeLimitMinutes: tests.timeLimitMinutes,
						passingScore: tests.passingScore,
						topicId: topics.id,
						topicSlug: topics.slug,
						topicTitle: topics.title,
					})
					.from(tests)
					.innerJoin(topics, eq(tests.topicId, topics.id))
					.where(
						and(
							eq(topics.slug, topicSlug),
							eq(topics.isActive, true),
							eq(tests.slug, testSlug),
							eq(tests.isPublished, true)
						)
					)
					.limit(1)
			)
			let test = testRows[0]
			if (!test && UUID_RE.test(testSlug)) {
				const fallbackRows = await withTransientDbRetry('public test by id fallback', () =>
					db
						.select({
							id: tests.id,
							slug: tests.slug,
							title: tests.title,
							description: tests.description,
							showCorrectAnswer: tests.showCorrectAnswer,
							timeLimitMinutes: tests.timeLimitMinutes,
							passingScore: tests.passingScore,
							topicId: topics.id,
							topicSlug: topics.slug,
							topicTitle: topics.title,
						})
						.from(tests)
						.innerJoin(topics, eq(tests.topicId, topics.id))
						.where(
							and(
								eq(topics.slug, topicSlug),
								eq(topics.isActive, true),
								eq(tests.id, testSlug),
								eq(tests.isPublished, true)
							)
						)
						.limit(1)
				)
				test = fallbackRows[0]
			}
		if (!test) {
			return res.status(404).json({ error: 'Test not found' })
		}

		// Проверить что тест назначен текущему пользователю (или пользователь — admin/teacher)
		const userId = req.authUser!.id
		const isAdmin = req.authUser!.roles?.some((r) => ['admin', 'teacher'].includes(r)) ?? false
		if (!isAdmin) {
				const assignment = await withTransientDbRetry('public test assignment check', () =>
					db
						.select()
						.from(testAssignments)
						.where(and(eq(testAssignments.testId, test.id), eq(testAssignments.userId, userId)))
						.limit(1)
				)
				if (assignment.length === 0) {
					return res.status(403).json({ error: 'Тест не назначен' })
				}
			}

			const questionRows = await withTransientDbRetry('public test questions list', () =>
				db
					.select({
						id: questions.id,
						type: questions.type,
						order: questions.order,
						points: questions.points,
						options: questions.options,
						matchingPairs: questions.matchingPairs,
						promptPath: questions.promptPath,
					})
					.from(questions)
					.where(eq(questions.testId, test.id))
					.orderBy(asc(questions.order))
			)
			const questionTypesMap = await withTransientDbRetry('public test question types', () =>
				getQuestionTypeMapForTest({ testId: test.id, includeInactive: true })
			)

		const questionsWithTexts = await Promise.all(
			questionRows.map(async (q) => {
				const promptCandidates = buildQuestionMarkdownCandidates({
					storedPath: q.promptPath,
					topicSlug: test.topicSlug,
					testSlug: test.slug,
					testId: test.id,
					questionId: q.id,
					fileName: 'prompt.md',
				})

				const promptText = await readFirstMarkdown(promptCandidates)
				const typeConfig = questionTypesMap[q.type]
				if (!typeConfig) {
					throw new Error(`Question type is not configured: ${q.type}`)
				}
				return {
					id: q.id,
					type: q.type,
					questionUiTemplate: typeConfig.uiTemplate,
					questionTypeTitle: typeConfig.title,
					order: q.order,
					points: q.points,
					options: q.options,
					matchingPairs: q.matchingPairs,
					promptText,
				}
			})
		)

		res.json({
			test,
			questions: questionsWithTexts,
		})
	} catch (e) {
		next(e)
	}
})

// GET /api/tests/public/tests/:id - получить тест и вопросы (БЕЗ ОТВЕТОВ)
router.get('/tests/:id', validateUUID('id'), sessionRequired(), async (req, res, next) => {
	try {
		const testId = req.params.id as string

		const testRows = await db
			.select({
				id: tests.id,
				slug: tests.slug,
				title: tests.title,
				description: tests.description,
				showCorrectAnswer: tests.showCorrectAnswer,
				timeLimitMinutes: tests.timeLimitMinutes,
				passingScore: tests.passingScore,
				topicId: topics.id,
				topicSlug: topics.slug,
				topicTitle: topics.title,
			})
			.from(tests)
			.innerJoin(topics, eq(tests.topicId, topics.id))
			.where(and(eq(tests.id, testId), eq(tests.isPublished, true), eq(topics.isActive, true)))
			.limit(1)

		const test = testRows[0]
		if (!test) {
			return res.status(404).json({ error: 'Test not found' })
		}

		// Проверить что тест назначен текущему пользователю (или пользователь — admin/teacher)
		const userId2 = req.authUser!.id
		const isAdmin2 = req.authUser!.roles?.some((r) => ['admin', 'teacher'].includes(r)) ?? false
		if (!isAdmin2) {
			const assignment = await db
				.select()
				.from(testAssignments)
				.where(and(eq(testAssignments.testId, test.id), eq(testAssignments.userId, userId2)))
				.limit(1)
			if (assignment.length === 0) {
				return res.status(403).json({ error: 'Тест не назначен' })
			}
		}

		const questionRows = await db
			.select({
				id: questions.id,
				type: questions.type,
				order: questions.order,
				points: questions.points,
				options: questions.options,
				matchingPairs: questions.matchingPairs,
				promptPath: questions.promptPath,
			})
			.from(questions)
			.where(eq(questions.testId, test.id))
			.orderBy(asc(questions.order))
		const questionTypesMap = await getQuestionTypeMapForTest({ testId: test.id, includeInactive: true })

		const questionsWithTexts = await Promise.all(
			questionRows.map(async (q) => {
				const promptCandidates = buildQuestionMarkdownCandidates({
					storedPath: q.promptPath,
					topicSlug: test.topicSlug,
					testSlug: test.slug,
					testId: test.id,
					questionId: q.id,
					fileName: 'prompt.md',
				})

				const promptText = await readFirstMarkdown(promptCandidates)
				const typeConfig = questionTypesMap[q.type]
				if (!typeConfig) {
					throw new Error(`Question type is not configured: ${q.type}`)
				}
				return {
					id: q.id,
					type: q.type,
					questionUiTemplate: typeConfig.uiTemplate,
					questionTypeTitle: typeConfig.title,
					order: q.order,
					points: q.points,
					options: q.options,
					matchingPairs: q.matchingPairs,
					promptText,
				}
			})
		)

		res.json({
			test,
			questions: questionsWithTexts,
		})
	} catch (e) {
		next(e)
	}
})

// GET /api/tests/public/tests/:id/attempts/me - история попыток текущего пользователя (с пагинацией)
router.get('/tests/:id/attempts/me', validateUUID('id'), sessionRequired(), async (req, res, next) => {
	try {
		const testId = req.params.id as string
		const userId = req.authUser?.id
		if (!userId) return res.status(401).json({ error: 'Unauthorized' })

		const offsetRaw = parseInt((req.query.offset as string) ?? '0', 10)
		const limitRaw = parseInt((req.query.limit as string) ?? '5', 10)
		const offset = isNaN(offsetRaw) || offsetRaw < 0 ? 0 : offsetRaw
		const limit = isNaN(limitRaw) || limitRaw < 1 ? 5 : Math.min(limitRaw, 100)

		const whereClause = and(eq(testAttempts.testId, testId), eq(testAttempts.userId, userId))

		const [totalResult, rows] = await Promise.all([
			db.select({ total: count() }).from(testAttempts).where(whereClause),
			db
				.select({
					id: testAttempts.id,
					earnedPoints: testAttempts.earnedPoints,
					totalPoints: testAttempts.totalPoints,
					scorePercentage: testAttempts.scorePercentage,
					passed: testAttempts.passed,
					submittedAt: testAttempts.submittedAt,
				})
				.from(testAttempts)
				.where(whereClause)
				.orderBy(desc(testAttempts.submittedAt))
				.limit(limit)
				.offset(offset),
		])

		const total = totalResult[0]?.total ?? 0
		res.json({ rows, total })
	} catch (e) {
		next(e)
	}
})

// GET /api/tests/public/tests/:id/chart-data - данные для графика (все попытки в диапазоне дат)
router.get('/tests/:id/chart-data', validateUUID('id'), sessionRequired(), async (req, res, next) => {
	try {
		const testId = req.params.id as string
		const userId = req.authUser?.id
		if (!userId) return res.status(401).json({ error: 'Unauthorized' })

		const fromParam = req.query.from as string | undefined
		const toParam = req.query.to as string | undefined

		const conditions = [eq(testAttempts.testId, testId), eq(testAttempts.userId, userId)]
		if (fromParam) {
			const fromDate = new Date(fromParam)
			if (!isNaN(fromDate.getTime())) {
				conditions.push(gte(testAttempts.submittedAt, fromDate))
			}
		}
		if (toParam) {
			const toDate = new Date(toParam)
			if (!isNaN(toDate.getTime())) {
				conditions.push(lte(testAttempts.submittedAt, toDate))
			}
		}

		// Fetch all attempts in range ordered ASC
		const allAttempts = await db
			.select({
				scorePercentage: testAttempts.scorePercentage,
				submittedAt: testAttempts.submittedAt,
			})
			.from(testAttempts)
			.where(and(...conditions))
			.orderBy(asc(testAttempts.submittedAt))

		// Group by date (YYYY-MM-DD), keep max/min/count per day
		const byDate = new Map<string, { scores: number[] }>()
		for (const a of allAttempts) {
			const dateKey = a.submittedAt.toISOString().slice(0, 10)
			if (!byDate.has(dateKey)) byDate.set(dateKey, { scores: [] })
			byDate.get(dateKey)!.scores.push(Math.round(a.scorePercentage ?? 0))
		}

		const data = [...byDate.entries()].map(([date, { scores }]) => ({
			date,
			maxScore: Math.max(...scores),
			minScore: Math.min(...scores),
			count: scores.length,
		}))

		res.json({ data })
	} catch (e) {
		next(e)
	}
})

// POST /api/tests/public/tests/:id/start - начать тестовую сессию (записать startedAt)
router.post('/tests/:id/start', validateUUID('id'), sessionRequired(), async (req, res, next) => {
	try {
		const testId = req.params.id as string
		const userId = req.authUser!.id

		const [test] = await db
			.select({ id: tests.id, timeLimitMinutes: tests.timeLimitMinutes })
			.from(tests)
			.where(and(eq(tests.id, testId), eq(tests.isPublished, true)))
			.limit(1)
		if (!test) return res.status(404).json({ error: 'Test not found' })

		// Return existing open session or create new one
		const existing = await db.query.testSessions.findFirst({
			where: and(eq(testSessions.testId, testId), eq(testSessions.userId, userId), isNull(testSessions.submittedAt)),
			orderBy: [desc(testSessions.startedAt)],
		})

		if (existing) {
			return res.json({
				startedAt: existing.startedAt.toISOString(),
				sessionId: existing.id,
				draftAnswers: existing.draftAnswers ?? null,
				draftLastQuestionId: existing.draftLastQuestionId ?? null,
				draftTelemetry: existing.draftTelemetry ?? null,
			})
		}

		const [session] = await db
			.insert(testSessions)
			.values({ testId, userId })
			.returning({ id: testSessions.id, startedAt: testSessions.startedAt })

		res.json({
			startedAt: session.startedAt.toISOString(),
			sessionId: session.id,
			draftAnswers: null,
			draftLastQuestionId: null,
			draftTelemetry: null,
		})
	} catch (e) {
		next(e)
	}
})

// PATCH /api/tests/public/tests/:id/sessions/:sessionId/answers - промежуточное сохранение черновика ответов в БД
const SaveDraftAnswerSchema = z
	.object({
		questionId: z.string().uuid().optional(),
		value: SubmitAnswerValueSchema.optional(),
		telemetry: TelemetrySchema.optional(),
	})
	.superRefine((data, ctx) => {
		const hasQuestion = data.questionId !== undefined
		const hasValue = data.value !== undefined
		if (hasQuestion !== hasValue || (!hasQuestion && data.telemetry === undefined)) {
			ctx.addIssue({
				code: z.ZodIssueCode.custom,
				message: 'Provide questionId with value, telemetry, or both',
			})
		}
	})

router.patch(
	'/tests/:id/sessions/:sessionId/answers',
	validateUUID('id'),
	validateUUID('sessionId'),
	sessionRequired(),
	async (req, res, next) => {
		try {
			const testId = req.params.id as string
			const sessionId = req.params.sessionId as string
			const userId = req.authUser!.id

			const parsed = SaveDraftAnswerSchema.safeParse(req.body)
			if (!parsed.success) {
				return res.status(400).json({ error: 'Bad request', details: parsed.error.flatten() })
			}
			const { questionId, value, telemetry } = parsed.data

			// Подтвердить что сессия принадлежит пользователю и ещё не submit-нута
			const session = await db.query.testSessions.findFirst({
				where: and(
					eq(testSessions.id, sessionId),
					eq(testSessions.testId, testId),
					eq(testSessions.userId, userId),
					isNull(testSessions.submittedAt)
				),
			})
			if (!session) {
				return res.status(404).json({ error: 'Session not found or already submitted' })
			}

			// Immutable merge: строим новый объект draft вместо мутации
			const existingDraft =
				session.draftAnswers && typeof session.draftAnswers === 'object' && !Array.isArray(session.draftAnswers)
					? (session.draftAnswers as Record<string, unknown>)
					: {}
			const nextDraft =
				questionId !== undefined && value !== undefined ? { ...existingDraft, [questionId]: value } : existingDraft
			const nextTelemetry = mergeTelemetryMaps(session.draftTelemetry, telemetry)

			await db
				.update(testSessions)
				.set({
					...(questionId !== undefined ? { draftAnswers: nextDraft, draftLastQuestionId: questionId } : {}),
					...(telemetry !== undefined ? { draftTelemetry: nextTelemetry } : {}),
					draftUpdatedAt: new Date(),
				})
				.where(eq(testSessions.id, sessionId))

			res.json({ ok: true })
		} catch (e) {
			next(e)
		}
	}
)

// POST /api/tests/public/tests/:id/submit - проверить ответы, сохранить попытку, вернуть результат
router.post('/tests/:id/submit', validateUUID('id'), sessionRequired(), async (req, res, next) => {
	try {
		const testId = req.params.id as string
		const userId = req.authUser?.id
		if (!userId) return res.status(401).json({ error: 'Unauthorized' })

		const parsed = SubmitAnswersSchema.safeParse(req.body)
		if (!parsed.success) {
			return res.status(400).json({ error: 'Bad request', details: parsed.error.flatten() })
		}

		const { answers: userAnswers, clientAttemptId, telemetry } = parsed.data

		const testRows = await db
			.select({
				id: tests.id,
				slug: tests.slug,
				topicSlug: topics.slug,
				passingScore: tests.passingScore,
				showCorrectAnswer: tests.showCorrectAnswer,
				timeLimitMinutes: tests.timeLimitMinutes,
			})
			.from(tests)
			.innerJoin(topics, eq(tests.topicId, topics.id))
			.where(and(eq(tests.id, testId), eq(tests.isPublished, true), eq(topics.isActive, true)))
			.limit(1)

		const test = testRows[0]
		if (!test) {
			return res.status(404).json({ error: 'Test not found' })
		}

		const session = await db.query.testSessions.findFirst({
			where: and(eq(testSessions.testId, testId), eq(testSessions.userId, userId)),
			orderBy: [desc(testSessions.startedAt)],
		})

		// --- Time limit enforcement ---
		if (test.timeLimitMinutes != null) {
			if (session?.submittedAt) {
				// Attempt already submitted via auto-submit — reject duplicate manual submit
				return res.status(409).json({
					error: 'TIME_EXPIRED_ALREADY_SUBMITTED',
					attemptId: session.attemptId,
				})
			}

			if (session) {
				const elapsedMinutes = (Date.now() - session.startedAt.getTime()) / 1000 / 60
				if (elapsedMinutes > test.timeLimitMinutes + GRACE_PERIOD_MINUTES) {
					// Auto-submit missed AND grace period expired — hard reject
					return res.status(422).json({ error: 'TIME_EXPIRED' })
				}
				// else: within grace period — accept (covers honest students with bad network)
			}
			// No session: test has time limit but student bypassed /start — accept (no session = no enforcement)
		}

		const questionTypesMap = await getQuestionTypeMapForTest({ testId: test.id, includeInactive: true })

		const questionRows = await db.select().from(questions).where(eq(questions.testId, test.id))
		const questionIds = questionRows.map((q) => q.id)
		if (questionIds.length === 0) {
			return res.status(404).json({ error: 'Questions not found' })
		}

		const correctAnswers = await db
			.select()
			.from(answerKeys)
			.where(and(inArray(answerKeys.questionId, questionIds), eq(answerKeys.isActive, true)))

		const correctAnswersMap = new Map(correctAnswers.map((ak) => [ak.questionId, ak.correctAnswer]))

		let totalPoints = 0
		let earnedPoints = 0
		const results: Array<{
			questionId: string
			isCorrect: boolean
			points: number
			earnedPoints: number
			userAnswer: unknown
			correctAnswer: unknown
			explanationText: string | null
		}> = []

		for (const q of questionRows) {
			const typeConfig = questionTypesMap[q.type]
			if (!typeConfig) {
				return res.status(500).json({ error: `Question type is not configured: ${q.type}` })
			}
			const correctAnswer = correctAnswersMap.get(q.id)
			const userAnswer = userAnswers[q.id] ?? null
			const score = scoreQuestionByType({
				questionType: q.type,
				userAnswer,
				correctAnswer,
				fallbackMaxPoints: Number(q.points ?? 0),
				questionTypesMap,
			})
			const points = score.maxPoints
			const questionEarnedPoints = score.earnedPoints
			const isCorrect = score.isCorrect

			totalPoints += points
			earnedPoints += questionEarnedPoints

			const explanationText = q.explanationPath
				? (await readFirstMarkdown(
						buildQuestionMarkdownCandidates({
							storedPath: q.explanationPath,
							topicSlug: test.topicSlug,
							testSlug: test.slug,
							testId: test.id,
							questionId: q.id,
							fileName: 'explanation.md',
						})
					)) || null
				: null

			results.push({
				questionId: q.id,
				isCorrect,
				points,
				earnedPoints: questionEarnedPoints,
				userAnswer,
				correctAnswer: isCorrect || !test.showCorrectAnswer ? null : correctAnswer,
				explanationText,
			})
		}

		const scorePercentage = totalPoints > 0 ? (earnedPoints / totalPoints) * 100 : 0
		const passed = test.passingScore == null ? true : scorePercentage >= Number(test.passingScore)
		const persistedTelemetry = mergeTelemetryMaps(session?.draftTelemetry, telemetry)

		const [attempt] = await db
			.insert(testAttempts)
			.values({
				testId: test.id,
				userId,
				answers: userAnswers,
				results,
				earnedPoints,
				totalPoints,
				scorePercentage,
				passed,
				clientAttemptId,
				telemetry: Object.keys(persistedTelemetry).length > 0 ? persistedTelemetry : null,
			})
			.onConflictDoNothing()
			.returning({
				id: testAttempts.id,
				submittedAt: testAttempts.submittedAt,
			})

		if (!attempt) {
			// Duplicate submission — clientAttemptId already used; fetch and return existing result
			const existing = await db.query.testAttempts.findFirst({
				where: and(eq(testAttempts.userId, userId), eq(testAttempts.clientAttemptId, clientAttemptId!)),
				columns: {
					id: true,
					submittedAt: true,
					earnedPoints: true,
					totalPoints: true,
					scorePercentage: true,
					passed: true,
					results: true,
				},
			})
			if (!existing) throw ApiError.internal('Idempotency fetch failed')
			return res.json(
				SubmitResultSchema.parse({
					attemptId: existing.id,
					submittedAt: existing.submittedAt instanceof Date ? existing.submittedAt.toISOString() : existing.submittedAt,
					earnedPoints: existing.earnedPoints,
					totalPoints: existing.totalPoints,
					scorePercentage: existing.scorePercentage,
					passed: existing.passed,
					results: existing.results,
				})
			)
		}

		// Mark session as submitted and clear draft (always, not only for timed tests)
		await db
			.update(testSessions)
			.set({
				submittedAt: new Date(),
				attemptId: attempt?.id ?? null,
				draftAnswers: null,
				draftLastQuestionId: null,
				draftTelemetry: null,
				draftUpdatedAt: null,
			})
			.where(and(eq(testSessions.testId, testId), eq(testSessions.userId, userId), isNull(testSessions.submittedAt)))

		const responsePayload = SubmitResultSchema.parse({
			attemptId: attempt.id,
			submittedAt: attempt.submittedAt instanceof Date ? attempt.submittedAt.toISOString() : attempt.submittedAt,
			earnedPoints,
			totalPoints,
			scorePercentage,
			passed,
			results,
		})
		res.json(responsePayload)
	} catch (e) {
		next(e)
	}
})

export default router
